services:
  backend:
    build: ./backend
    container_name: weather_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis

  celery:
    build: ./backend
    container_name: weather_celery
    command: celery -A worker.celery_app.celery_app worker --loglevel=info -Q weather
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - db

  db:
    image: postgres:16
    container_name: weather_db
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - weather_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: weather_redis
    ports:
      - "6379:6379"

volumes:
  weather_postgres_data: